In [2]:
from common import Data

In [4]:
df = Data.get_nwsl_player_stats()

In [10]:
df

,season,date,home,away,player,team,number,position,is_starter,accurate_keeper_throws,...,att_obp_goal,att_pen_miss,assist_post,att_lg_left,back_pass,corner_kicks,penalty_saved,has_full_stats,goal_assists,is_playoffs
0,2016,2016-04-16,HOU,CHI,Alyssa Naeher,CHI,1,Goalkeeper,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
1,2016,2016-04-16,HOU,CHI,Casey Krueger,CHI,6,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
2,2016,2016-04-16,HOU,CHI,Julie Ertz,CHI,8,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
3,2016,2016-04-16,HOU,CHI,Samantha Johnson,CHI,16,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
4,2016,2016-04-16,HOU,CHI,Arin Wright,CHI,3,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38722,2024,2024-04-27,UTA,HOU,Michelle Alozie,HOU,11,Striker,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
38726,2024,2024-04-27,UTA,HOU,Sophie Hirst,HOU,20,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
38727,2024,2024-04-27,UTA,HOU,Yuki Nagasato,HOU,14,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
38728,2024,2024-04-27,UTA,HOU,BÃ¡rbara Olivieri,HOU,15,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False
38730,2024,2024-04-27,UTA,HOU,Amanda West,HOU,16,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,False

In [7]:
list(filter(lambda x : "foul" in x, df.columns))

['attempted_tackle_foul',
 'fouls',
 'was_fouled',
 'fouled_final_third',
 'foul_throw_in']

In [15]:
df.groupby(["player", "season"]).agg(fouls=("fouls", "sum")).reset_index().sort_values("fouls", ascending=False)

               player season  fouls
1678      Rosie White   2017   47.0
1362   McCall Zerboni   2017   44.0
1766  Savannah DeMelo   2022   42.0
1561    Nikki Stanton   2018   42.0
1215    Lindsey Horan   2018   41.0
...               ...    ...    ...
779       Hailie Mace   2024    0.0
781      Haley Bugeja   2022    0.0
782      Haley Bugeja   2023    0.0
785    Haley Kopmeyer   2016    0.0
1013  Katelyn Rowland   2021    0.0

[2027 rows x 3 columns]