In [61]:
import pandas as pd
import numpy as np
from common import Data
from datetime import datetime, timedelta

In [64]:
year = "2023"

In [65]:
df = Data.get_nwsl_player_stats(season=year)
df = df[df["date"] < "2023-10-18"]
df

<ipython-input-65-60dfa96c2ab3>:1: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  df = Data.get_nwsl_player_stats(season=year)

,season,date,home,away,player,team,number,position,is_starter,accurate_keeper_throws,...,dive_catch,att_lg_centre,foul_throw_in,assist_handball_won,att_pen_post,att_obp_goal,att_pen_miss,assist_post,att_lg_left,back_pass
22528,2023,2023-04-15,NC,WAS,Tara McKeown,WAS,9,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22529,2023,2023-04-15,NC,WAS,Dorian Bailey,WAS,19,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22530,2023,2023-04-15,NC,WAS,Marissa Sheva,WAS,25,Midfielder,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22531,2023,2023-04-15,NC,WAS,Andi Sullivan,WAS,12,Midfielder,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22532,2023,2023-04-15,NC,WAS,In√®s Jaurena,WAS,7,Midfielder,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35305,2023,2023-10-15,WAS,NC,Kiki Pickett,NC,23,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35306,2023,2023-10-15,WAS,NC,Brittany Ratcliffe,NC,11,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35307,2023,2023-10-15,WAS,NC,Katelyn Rowland,NC,99,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35308,2023,2023-10-15,WAS,NC,Brianna Pinto,NC,8,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35309,2023,2023-10-15,WAS,NC,Frankie Tagliaferri,NC,19,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Get range of dates
date_list = pd.date_range(df["date"].min(), df["date"].max(), freq='D')
date_list

DatetimeIndex(['2023-03-25', '2023-03-26', '2023-03-27', '2023-03-28',
               '2023-03-29', '2023-03-30', '2023-03-31', '2023-04-01',
               '2023-04-02', '2023-04-03',
               ...
               '2023-10-06', '2023-10-07', '2023-10-08', '2023-10-09',
               '2023-10-10', '2023-10-11', '2023-10-12', '2023-10-13',
               '2023-10-14', '2023-10-15'],
              dtype='datetime64[ns]', length=205, freq='D')

In [43]:
# Get all goal scorers
scorers = df.groupby("player").agg({"goals": "sum"})
scorers = scorers[scorers["goals"] > 0]
scorers = scorers.sort_values(["goals"], ascending=False)
scorers

                              goals
player
Sophia Smith                   11.0
D√©bora Cristiane de Oliveira    9.0
Kerolin Nicoli Israel Ferraz    9.0
Ashley Hatch                    9.0
Alex Morgan                     7.0
...                             ...
Kayla Sharples                  1.0
Julie Ertz                      1.0
Jordan Baggett                  1.0
Joelle Anderson                 1.0
Kylie Strom                     1.0

[128 rows x 1 columns]

In [44]:
# Create empty table
res = pd.DataFrame([], columns=date_list, index=scorers.index)
res

,2023-03-25,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,...,2023-10-06,2023-10-07,2023-10-08,2023-10-09,2023-10-10,2023-10-11,2023-10-12,2023-10-13,2023-10-14,2023-10-15
player,,,,,,,,,,,,,,,,,,,,,
Sophia Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D√©bora Cristiane de Oliveira,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kerolin Nicoli Israel Ferraz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ashley Hatch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alex Morgan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kayla Sharples,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Julie Ertz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jordan Baggett,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Joelle Anderson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kylie Strom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
# Fill in data
for d in date_list:
    today = str(d.date())
    yesterday = str((d - timedelta(days=1)).date())
    if today == str(df["date"].min()):
        res[today] = 0
    else:
        res[today] = res[yesterday]
        
    for i, row in df[df["date"] == today].iterrows():
        if row["player"] in scorers.index and not np.isnan(row["goals"]):
            res.loc[row["player"], d] = res.loc[row["player"], d] + row["goals"]
        
res

,2023-03-25,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,...,2023-10-06,2023-10-07,2023-10-08,2023-10-09,2023-10-10,2023-10-11,2023-10-12,2023-10-13,2023-10-14,2023-10-15
player,,,,,,,,,,,,,,,,,,,,,
Sophia Smith,0,1,1,1,1,1,1,4,4,4,...,11,11,11,11,11,11,11,11,11,11
D√©bora Cristiane de Oliveira,0,0,0,0,0,0,0,0,0,0,...,8,9,9,9,9,9,9,9,9,9
Kerolin Nicoli Israel Ferraz,0,0,0,0,0,0,0,1,1,1,...,9,9,9,9,9,9,9,9,9,9
Ashley Hatch,0,0,0,0,0,0,0,2,2,2,...,9,9,9,9,9,9,9,9,9,9
Alex Morgan,1,1,1,1,1,1,1,3,3,3,...,6,6,6,6,6,6,6,6,6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kayla Sharples,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,1
Julie Ertz,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Jordan Baggett,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Joelle Anderson,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Kylie Strom,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

In [66]:
res.to_csv("golden_boot_" + year + ".csv")