In [1]:
from common import Data

In [2]:
df = Data.get_nwsl_player_stats(include_playoffs=False, include_cups=False, season="2022")
df

/home/agale/soccer-library/src/common/data.py:38: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(files("common.data-src").joinpath("nwsl_match_stats.csv"))

,season,date,home,away,player,team,number,position,is_starter,accurate_keeper_throws,...,att_lg_centre,foul_throw_in,assist_handball_won,att_pen_post,att_obp_goal,att_pen_miss,assist_post,att_lg_left,back_pass,is_playoffs
22985,2022,2022-04-29,LA,NC,DiDi Haračić,LA,13,Goalkeeper,True,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22986,2022,2022-04-29,LA,NC,Ali Riley,LA,5,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22987,2022,2022-04-29,LA,NC,Vanessa Gilles,LA,4,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22988,2022,2022-04-29,LA,NC,Megan Reid,LA,2,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22989,2022,2022-04-29,LA,NC,Jasmyne Spencer,LA,3,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28197,2022,2022-10-02,CHI,LA,Simone Charley,LA,7,Striker,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28198,2022,2022-10-02,CHI,LA,Hope Breslin,LA,26,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28199,2022,2022-10-02,CHI,LA,Madison Hammond,LA,99,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28205,2022,2022-10-02,CHI,LA,Tyler Lussi,LA,20,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28206,2022,2022-10-02,CHI,LA,M. A. Vignola,LA,16,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [4]:
df = df[(df["team"] == "LA") | (df["team"] == "SD")]
df

,season,date,home,away,player,team,number,position,is_starter,accurate_keeper_throws,...,att_lg_centre,foul_throw_in,assist_handball_won,att_pen_post,att_obp_goal,att_pen_miss,assist_post,att_lg_left,back_pass,is_playoffs
22985,2022,2022-04-29,LA,NC,DiDi Haračić,LA,13,Goalkeeper,True,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22986,2022,2022-04-29,LA,NC,Ali Riley,LA,5,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22987,2022,2022-04-29,LA,NC,Vanessa Gilles,LA,4,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22988,2022,2022-04-29,LA,NC,Megan Reid,LA,2,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22989,2022,2022-04-29,LA,NC,Jasmyne Spencer,LA,3,Defender,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28197,2022,2022-10-02,CHI,LA,Simone Charley,LA,7,Striker,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28198,2022,2022-10-02,CHI,LA,Hope Breslin,LA,26,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28199,2022,2022-10-02,CHI,LA,Madison Hammond,LA,99,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28205,2022,2022-10-02,CHI,LA,Tyler Lussi,LA,20,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
28206,2022,2022-10-02,CHI,LA,M. A. Vignola,LA,16,Substitute,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [8]:
df = df.groupby(["player", "team"]).agg(
    minutes=("mins_played", "sum")
).reset_index().sort_values(["team", "player"]).reset_index(drop=True)
df

                       player team  minutes
0                   Ali Riley   LA   1504.0
1               Allyson Swaby   LA     21.0
2               Almuth Schult   LA     90.0
3                Cari Roccaro   LA   1511.0
4              Christen Press   LA    506.0
5               Claire Emslie   LA    783.0
6           Clarisse Le Bihan   LA   1053.0
7            Dani Weatherholt   LA   1653.0
8                DiDi Haračić   LA   1710.0
9                Hope Breslin   LA     73.0
10            Jasmyne Spencer   LA    742.0
11                   Jun Endo   LA   1745.0
12              Katie Cousins   LA      1.0
13                 Lily Nabet   LA    205.0
14              M. A. Vignola   LA     17.0
15            Madison Hammond   LA    229.0
16                 Megan Reid   LA   1800.0
17                Miri Taylor   LA    342.0
18              Paige Nielsen   LA   1280.0
19         Savannah McCaskill   LA   1661.0
20             Simone Charley   LA    958.0
21  Stefany Ferrer van Ginkel   LA     19.0
22              Sydney Leroux   LA    182.0
23                Tyler Lussi   LA   1280.0
24             Vanessa Gilles   LA    424.0
25            Abby Dahlkemper   SD    533.0
26                Alex Morgan   SD   1267.0
27                 Amirah Ali   SD    481.0
28               Belle Briede   SD   1143.0
29              Carly Telford   SD    360.0
30          Christen Westphal   SD   1600.0
31           Emily van Egmond   SD   1755.0
32                Jaedyn Shaw   SD    263.0
33               Jodie Taylor   SD    432.0
34            Kailen Sheridan   SD   1439.0
35              Kaleigh Riehl   SD   1532.0
36              Katie Johnson   SD    505.0
37             Kelsey Turnbow   SD   1143.0
38             Kristen McNabb   SD   1733.0
39            Madison Pogarch   SD    298.0
40             Makenzy Doniak   SD    641.0
41           Marleen Schimmer   SD    348.0
42                   Mia Gyau   SD    129.0
43                Naomi Girma   SD   1530.0
44            Sofia Jakobsson   SD    906.0
45              Sydney Pulver   SD      7.0
46            Taylor Kornieck   SD   1203.0
47              Tegan McGrady   SD    509.0

In [9]:
df["acquired"] = ""
df

                       player team  minutes acquired
0                   Ali Riley   LA   1504.0
1               Allyson Swaby   LA     21.0
2               Almuth Schult   LA     90.0
3                Cari Roccaro   LA   1511.0
4              Christen Press   LA    506.0
5               Claire Emslie   LA    783.0
6           Clarisse Le Bihan   LA   1053.0
7            Dani Weatherholt   LA   1653.0
8                DiDi Haračić   LA   1710.0
9                Hope Breslin   LA     73.0
10            Jasmyne Spencer   LA    742.0
11                   Jun Endo   LA   1745.0
12              Katie Cousins   LA      1.0
13                 Lily Nabet   LA    205.0
14              M. A. Vignola   LA     17.0
15            Madison Hammond   LA    229.0
16                 Megan Reid   LA   1800.0
17                Miri Taylor   LA    342.0
18              Paige Nielsen   LA   1280.0
19         Savannah McCaskill   LA   1661.0
20             Simone Charley   LA    958.0
21  Stefany Ferrer van Ginkel   LA     19.0
22              Sydney Leroux   LA    182.0
23                Tyler Lussi   LA   1280.0
24             Vanessa Gilles   LA    424.0
25            Abby Dahlkemper   SD    533.0
26                Alex Morgan   SD   1267.0
27                 Amirah Ali   SD    481.0
28               Belle Briede   SD   1143.0
29              Carly Telford   SD    360.0
30          Christen Westphal   SD   1600.0
31           Emily van Egmond   SD   1755.0
32                Jaedyn Shaw   SD    263.0
33               Jodie Taylor   SD    432.0
34            Kailen Sheridan   SD   1439.0
35              Kaleigh Riehl   SD   1532.0
36              Katie Johnson   SD    505.0
37             Kelsey Turnbow   SD   1143.0
38             Kristen McNabb   SD   1733.0
39            Madison Pogarch   SD    298.0
40             Makenzy Doniak   SD    641.0
41           Marleen Schimmer   SD    348.0
42                   Mia Gyau   SD    129.0
43                Naomi Girma   SD   1530.0
44            Sofia Jakobsson   SD    906.0
45              Sydney Pulver   SD      7.0
46            Taylor Kornieck   SD   1203.0
47              Tegan McGrady   SD    509.0

In [10]:
df.to_csv("data/LA_SD_expansion.csv", index=False)