In [1]:
import nwslpy
import pandas as pd
import datetime

# Read 2016-now data from nwslR

In [2]:
teams = nwslpy.load_teams()
teams

,team_name,team_name_short,team_club_name,team_abbreviation,first_season,last_season,last_updated
team_id,,,,,,,
1,Boston Breakers,Boston Breakers,Boston Breakers,BOS,2016,2017,2023-02-18
2,Chicago Red Stars,Chicago Red Stars,Chicago Red Stars,CHI,2016,2022,2023-02-18
3,FC Kansas City,FC Kansas City,FC Kansas City,KC,2016,2017,2023-02-18
4,Houston Dash,Houston Dash,Houston Dash,HOU,2016,2022,2023-02-18
5,NJ/NY Gotham FC,NJ/NY Gotham FC,Gotham FC,NJY,2016,2022,2023-02-18
6,OL Reign,OL Reign,OL Reign,RGN,2016,2022,2023-02-18
7,Orlando Pride,Orlando Pride,Orlando Pride,ORL,2016,2022,2023-02-18
8,Portland Thorns FC,Portland Thorns FC,Portland Thorns,POR,2016,2022,2023-02-18
9,Washington Spirit,Washington Spirit,Washington Spirit,WAS,2016,2022,2023-02-18
10,Western New York Flash,Western New York Flash,Western New York Flash,WNY,2016,2016,2023-02-18
11,North Carolina Courage,North Carolina Courage,North Carolina Courage,NC,2017,2022,2023-02-18
12,Utah Royals FC,Utah Royals FC,Utah Royals,UTA,2018,2020,2023-02-18
13,Kansas City Current,Kansas City Current,Kansas City Current,KCC,2021,2022,2023-02-18
14,Racing Louisville FC,Racing Louisville FC,Racing Louisville,LOU,2021,2022,2023-02-18
15,Angel City FC,Angel City FC,Angel City,LA,2022,2022,2023-02-18
16,San Diego Wave FC,San Diego Wave FC,San Diego Wave,SD,2022,2022,2023-02-18

In [3]:
matches = nwslpy.load_matches()
matches.head()

,home_team_id,away_team_id,kickoff,time,stadium,city,year,season,home_team_score,away_team_score,home_penalty_score,away_penalty_score,won_on_penalites,last_updated
match_id,,,,,,,,,,,,,,
washington-spirit-vs-boston-breakers-2016-04-16,9,1,2016-04-16 19:00:00,19:00:00,NaN,NaN,2016,2016,1,0,0,0,False,2023-03-12
houston-dash-vs-chicago-red-stars-2016-04-16,4,2,2016-04-16 20:30:00,20:30:00,Shell Energy Stadium,"Houston, Texas",2016,2016,3,1,0,0,False,2023-03-12
fc-kansas-city-vs-western-new-york-flash-2016-04-16,3,10,2016-04-16 20:30:00,20:30:00,Children's Mercy Park,"Kansas City, Kansas",2016,2016,0,1,0,0,False,2023-03-12
seatle-reign-fc-vs-sky-blue-fc-2016-04-17,6,5,2016-04-17 19:00:00,19:00:00,UW Medicine Pitch at Memorial Stadium,Seattle,2016,2016,1,2,0,0,False,2023-03-12
portland-thorns-fc-vs-orlando-pride-2016-04-17,8,7,2016-04-17 22:00:00,22:00:00,Providence Park,"Portland, Oregon",2016,2016,2,1,0,0,False,2023-03-12

In [4]:
merged = (
    matches.merge(
        teams[["team_abbreviation"]], left_on="home_team_id", right_on="team_id"
    )
    .rename(columns={"team_abbreviation": "home_team"})
    .merge(teams[["team_abbreviation"]], left_on="away_team_id", right_on="team_id")
    .rename(
        columns={
            "team_abbreviation": "away_team",
        }
    )
    .sort_values("kickoff")
)

merged = merged[
    [
        "kickoff",
        "season",
        "home_team",
        "away_team",
        "home_team_score",
        "away_team_score",
        "home_penalty_score",
        "away_penalty_score",
    ]
]
merged

,kickoff,season,home_team,away_team,home_team_score,away_team_score,home_penalty_score,away_penalty_score
0,2016-04-16 19:00:00,2016,WAS,BOS,1,0,0,0
454,2016-04-16 20:30:00,2016,KC,WNY,0,1,0,0
374,2016-04-16 20:30:00,2016,HOU,CHI,3,1,0,0
281,2016-04-17 19:00:00,2016,RGN,NJY,1,2,0,0
211,2016-04-17 22:00:00,2016,POR,ORL,2,1,0,0
...,...,...,...,...,...,...,...,...
675,2022-10-16 17:00:00,2022,HOU,KCC,1,2,0,0
450,2022-10-16 22:00:00,2022,SD,CHI,2,1,0,0
721,2022-10-23 17:00:00,2022,POR,SD,2,1,0,0
678,2022-10-23 19:30:00,2022,RGN,KCC,0,2,0,0
683,2022-10-29 19:59:00,2022,POR,KCC,2,0,0,0

In [5]:
# Calculate whether each game is part of the playoffs
playoffs = {
    "2023 Challenge Cup": datetime.date(2023, 8, 7),
    "2023": datetime.date(2023, 10, 21),
    "2022 Challenge Cup": datetime.date(2022, 5, 3),
    "2022": datetime.date(2022, 10, 15),
    "2021 Challenge Cup": datetime.date(2021, 5, 7),
    "2021": datetime.date(2021, 11, 6),
    "2020 Fall Series": datetime.date(2020, 10, 18),
    "2020 Challenge Cup": datetime.date(2020, 7, 16),
    "2019": datetime.date(2019, 10, 19),
    "2018": datetime.date(2018, 9, 14),
    "2017": datetime.date(2017, 10, 6),
    "2016": datetime.date(2016, 9, 29),
}

merged["is_playoff"] = merged.apply(
    lambda row: row["kickoff"] > playoffs[row["season"]], axis=1
)
merged

<ipython-input-5-436758568535>:16: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior.  In a future version these will be considered non-comparable.Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  lambda row: row["kickoff"] > playoffs[row["season"]], axis=1

,kickoff,season,home_team,away_team,home_team_score,away_team_score,home_penalty_score,away_penalty_score,is_playoff
0,2016-04-16 19:00:00,2016,WAS,BOS,1,0,0,0,False
454,2016-04-16 20:30:00,2016,KC,WNY,0,1,0,0,False
374,2016-04-16 20:30:00,2016,HOU,CHI,3,1,0,0,False
281,2016-04-17 19:00:00,2016,RGN,NJY,1,2,0,0,False
211,2016-04-17 22:00:00,2016,POR,ORL,2,1,0,0,False
...,...,...,...,...,...,...,...,...,...
675,2022-10-16 17:00:00,2022,HOU,KCC,1,2,0,0,True
450,2022-10-16 22:00:00,2022,SD,CHI,2,1,0,0,True
721,2022-10-23 17:00:00,2022,POR,SD,2,1,0,0,True
678,2022-10-23 19:30:00,2022,RGN,KCC,0,2,0,0,True
683,2022-10-29 19:59:00,2022,POR,KCC,2,0,0,0,True

# Read 2013-2015 data from fbref

In [6]:
years = ["2013", "2014", "2015"]

fbref = pd.DataFrame([]);

for year in years:
    df = pd.read_csv("data/" + year + ".csv")
    teams = {
        "Dash": "HOU",
        "Thorns": "POR",
        "Spirit": "WAS",
        "Reign": "RGN",
        "Kansas City": "KC",
        "Sky Blue": "NJY",
        "Flash": "WNY",
        "Boston": "BOS",
        "Red Stars": "CHI",
    }
    df["home_team"] = df["Home"].apply(lambda x: teams[x])
    df["away_team"] = df["Away"].apply(lambda x: teams[x])
    df["kickoff"] = df.apply(
        lambda row: row["Date"] + " " + row["Time"].split(" ")[0], axis=1
    )
    df["kickoff"] = pd.to_datetime(df["kickoff"])
    df["home_team_score"] = df.apply(lambda row: int(row["Score"].split("–")[0]), axis=1)
    df["away_team_score"] = df.apply(lambda row: int(row["Score"].split("–")[1]), axis=1)
    df["home_penalty_score"] = 0
    df["away_penalty_score"] = 0
    df["season"] = year
    df["is_playoff"] = df["Round"] != "Regular Season"

    df = df[
        [
            "kickoff",
            "season",
            "home_team",
            "away_team",
            "home_team_score",
            "away_team_score",
            "home_penalty_score",
            "away_penalty_score",
            "is_playoff"
        ]
    ]
    
    fbref = fbref.append(df)
fbref

,kickoff,season,home_team,away_team,home_team_score,away_team_score,home_penalty_score,away_penalty_score,is_playoff
0,2013-04-14 17:00:00,2013,CHI,RGN,1,1,0,0,False
1,2013-04-14 18:00:00,2013,NJY,WNY,1,0,0,0,False
2,2013-04-14 18:30:00,2013,BOS,WAS,1,1,0,0,False
3,2013-04-13 19:35:00,2013,KC,POR,1,1,0,0,False
4,2013-04-20 19:00:00,2013,WAS,WNY,1,1,0,0,False
...,...,...,...,...,...,...,...,...,...
88,2015-09-05 19:00:00,2015,WAS,RGN,1,2,0,0,False
89,2015-09-06 19:00:00,2015,CHI,HOU,1,1,0,0,False
90,2015-09-13 19:00:00,2015,CHI,KC,0,3,0,0,True
91,2015-09-13 19:00:00,2015,RGN,WAS,3,0,0,0,True
92,2015-10-01 19:00:00,2015,KC,RGN,1,0,0,0,True

In [7]:
# Write combined dataset to file
fbref.append(merged).to_csv("data/all_matches.csv", index=False)