In [1]:
from itscalledsoccer.client import AmericanSoccerAnalysis

In [2]:
asa_client = AmericanSoccerAnalysis()

Gathering all players
Gathering all teams
Gathering all stadia
Gathering all managers
Gathering all referees
Finished initializing client

In [4]:
games = asa_client.get_games(leagues="nwsl")
games

,game_id,date_time_utc,home_score,away_score,home_team_id,away_team_id,referee_id,stadium_id,home_manager_id,away_manager_id,expanded_minutes,season_name,matchday,attendance,knockout_game,last_updated_utc,extra_time,home_penalties,away_penalties,penalties
0,gpMO0D1O5z,2022-10-29 23:59:00 UTC,2,0,Pk5LeeNqOW,4wM4rZdqjB,Xj5YWgaQbd,xW5pwORMg1,xW5pVglQg1,0x5gj0ZM7O,96,2022,23,0,True,2022-10-30 03:31:36 UTC,NaN,NaN,NaN,NaN
1,7VqG89LAQv,2022-10-23 23:30:00 UTC,0,2,7vQ7BBzqD1,4wM4rZdqjB,a35r3kGqL6,9Yqda07QvJ,OlMlY7P5Lz,0x5gj0ZM7O,100,2022,22,21491,True,2022-10-24 01:47:51 UTC,NaN,NaN,NaN,NaN
2,0Oq66j2rq6,2022-10-23 21:00:00 UTC,2,1,Pk5LeeNqOW,7VqG1lYMvW,4wM4mGg5jB,p6qbX06M0G,xW5pVglQg1,7VqGDAjQvW,102,2022,22,22035,True,2022-10-27 15:54:32 UTC,NaN,NaN,NaN,NaN
3,0x5gEKJ7Q7,2022-10-17 02:00:00 UTC,2,1,7VqG1lYMvW,KPqjw8PQ6v,0x5gNljM7O,Oa5wKXY514,7VqGDAjQvW,wvq9bvaQWn,138,2022,21,26215,True,2022-10-21 13:06:03 UTC,1.0,NaN,NaN,NaN
4,NWMW0Zge5l,2022-10-16 21:00:00 UTC,1,2,4JMAk47qKg,4wM4rZdqjB,NWMWR3DQlz,0x5g6ojM7O,9vQ2r1LQK6,0x5gj0ZM7O,105,2022,21,21284,True,2022-10-19 21:49:31 UTC,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,jYQJ6y4EQG,2016-04-18 02:00:00 UTC,2,1,Pk5LeeNqOW,XVqKeVKM01,0Oq6AZ756D,p6qbX06M0G,9z5krYJMA3,e7Mz3xj5r0,98,2016,1,16073,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
805,Xj5Y3zRxQb,2016-04-17 23:00:00 UTC,1,2,7vQ7BBzqD1,raMyrr25d2,2vQ1lzbqrA,gOMnlReqwN,OlMlY7P5Lz,wvq9mKNqWn,96,2016,1,3987,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
806,e7MzRogPMr,2016-04-17 00:30:00 UTC,0,1,kRQaWa15KZ,xW5pwDBMg1,0Oq6mXx56D,NPqxy6XQ9d,vzqo3mNqap,2lqREma5r0,95,2016,1,8022,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
807,N6MmLzjwQE,2016-04-17 00:30:00 UTC,3,1,4JMAk47qKg,KPqjw8PQ6v,7VqGEeeMvW,0x5g6ojM7O,Xj5Yx9RMbd,gOMnwm85wN,96,2016,1,7740,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
808,ljqE3k0YMx,2016-04-16 23:00:00 UTC,1,0,aDQ0lzvQEv,4wM4Ezg5jB,7VqGv4A5vW,vzqoGO7qap,0Oq6mKg56D,9YqdEXRQvJ,94,2016,1,3578,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN

In [7]:
asa_client.get_team_xpass(leagues="nwsl")

,team_id,count_games,attempted_passes_for,pass_completion_percentage_for,xpass_completion_percentage_for,passes_completed_over_expected_for,passes_completed_over_expected_p100_for,avg_vertical_distance_for,attempted_passes_against,pass_completion_percentage_against,xpass_completion_percentage_against,passes_completed_over_expected_against,passes_completed_over_expected_p100_against,avg_vertical_distance_against,passes_completed_over_expected_difference,avg_vertical_distance_difference
0,4JMAk47qKg,158,68501,0.7166,0.7228,-430.7925,-0.6289,8.5674,76744,0.7476,0.7410,508.3589,0.6624,7.5795,-939.1513,0.9879
1,4wM4Ezg5jB,44,17835,0.6876,0.6970,-167.2721,-0.9379,9.8061,19631,0.7166,0.7143,44.0219,0.2242,8.6808,-211.2939,1.1252
2,4wM4rZdqjB,56,22938,0.6943,0.7124,-415.3457,-1.8107,8.8520,25490,0.7232,0.7232,1.7153,0.0067,8.0800,-417.0610,0.7720
3,7vQ7BBzqD1,159,77750,0.7288,0.7248,311.2167,0.4003,7.8392,71271,0.7066,0.7135,-489.0296,-0.6862,8.6754,800.2463,-0.8362
4,7VqG1lYMvW,27,11698,0.6990,0.6988,1.9606,0.0168,8.8165,11629,0.7065,0.7164,-115.5927,-0.9940,8.4303,117.5533,0.3862
5,aDQ0lzvQEv,161,76821,0.7380,0.7397,-133.5581,-0.1739,7.6958,72242,0.7204,0.7210,-47.1159,-0.0652,8.1883,-86.4422,-0.4926
6,eV5D2w9QKn,57,28187,0.7434,0.7434,1.0432,0.0037,7.4815,25598,0.7129,0.7175,-116.6313,-0.4556,8.3737,117.6745,-0.8921
7,eV5DR6YQKn,55,23921,0.7153,0.7260,-257.1433,-1.0750,8.2630,26063,0.7483,0.7381,264.6026,1.0152,7.4891,-521.7459,0.7740
8,KPqjw8PQ6v,166,73576,0.7004,0.7053,-360.3823,-0.4898,8.6782,78219,0.7163,0.7237,-573.4907,-0.7332,8.1612,213.1083,0.5170
9,kRQa8JOqKZ,27,11981,0.7289,0.7297,-9.6578,-0.0806,7.8205,12392,0.7280,0.7253,32.8639,0.2652,7.3988,-42.5217,0.4217
10,kRQaWa15KZ,44,19344,0.7174,0.7255,-157.1442,-0.8124,8.6402,20841,0.7233,0.7234,-0.4938,-0.0024,8.4528,-156.6504,0.1873
11,Pk5LeeNqOW,164,76525,0.7267,0.7172,720.5953,0.9416,8.1853,70659,0.6965,0.7007,-297.1276,-0.4205,8.9617,1017.7229,-0.7765
12,raMyrr25d2,159,74144,0.7396,0.7368,210.3803,0.2837,7.9144,76476,0.7490,0.7391,761.0110,0.9951,7.4111,-550.6307,0.5033
13,XVqKeVKM01,152,67568,0.7250,0.7235,102.8683,0.1522,8.1388,68665,0.7347,0.7308,262.0409,0.3816,7.7879,-159.1725,0.3510
14,xW5pwDBMg1,22,8541,0.6068,0.6316,-211.4987,-2.4763,11.8954,9606,0.6621,0.6933,-299.7830,-3.1208,10.7767,88.2843,1.1188
15,zeQZeazqKw,145,68742,0.7301,0.7251,342.7169,0.4986,7.8030,62546,0.7058,0.7119,-387.3632,-0.6193,8.9162,730.0801,-1.1132

In [5]:
teams = asa_client.get_teams(leagues="nwsl")
teams

,team_id,team_name,team_short_name,team_abbreviation,competition
0,4JMAk47qKg,Houston Dash,Houston,HOU,nwsl
1,4wM4Ezg5jB,Boston Breakers,Boston,BOS,nwsl
2,4wM4rZdqjB,Kansas City Current,Kansas City,KC,nwsl
3,7vQ7BBzqD1,OL Reign,Reign,RGN,nwsl
4,7VqG1lYMvW,San Diego Wave FC,San Diego,SD,nwsl
5,aDQ0lzvQEv,Washington Spirit,Washington,WAS,nwsl
6,eV5D2w9QKn,Utah Royals FC,Utah Royals,UTA,nwsl
7,eV5DR6YQKn,Racing Louisville FC,Louisville,LOU,nwsl
8,KPqjw8PQ6v,Chicago Red Stars,Chicago,CHI,nwsl
9,kRQa8JOqKZ,Angel City FC,Angel City,LA,nwsl
10,kRQaWa15KZ,FC Kansas City,Kansas City,KC,nwsl
11,Pk5LeeNqOW,Portland Thorns FC,Portland,POR,nwsl
12,raMyrr25d2,NJ/NY Gotham FC,Gotham FC,NJY,nwsl
13,XVqKeVKM01,Orlando Pride,Orlando,ORL,nwsl
14,xW5pwDBMg1,Western New York Flash,Western New York,WNY,nwsl
15,zeQZeazqKw,North Carolina Courage,North Carolina,NC,nwsl

In [6]:
players = asa_client.get_players(leagues="nwsl")
players

,player_id,player_name,birth_date,height_ft,height_in,nationality,primary_broad_position,primary_general_position,season_name,secondary_broad_position,secondary_general_position,weight_lb,competition
0,0Oq632XPQ6,Jenna Hellstrom,1995-04-02,5.0,6.0,Canada,DF,FB,2020,NaN,NaN,NaN,nwsl
1,0Oq63d8XQ6,Maddie Huster,1996-07-05,5.0,4.0,USA,NaN,NaN,{},NaN,NaN,NaN,nwsl
2,0Oq63dogQ6,Paige Monaghan,1996-11-13,5.0,7.0,USA,MF,W,"[2019, 2020, 2021, 2022]",NaN,NaN,NaN,nwsl
3,0Oq63dpzQ6,Erin Yenney,1992-10-20,5.0,7.0,USA,FW,W,2018,MF,W,NaN,nwsl
4,0Oq63NGdQ6,Kate Del Fava,1998-07-23,5.0,9.0,USA,DF,FB,"[2020, 2021, 2022]",NaN,CB,NaN,nwsl
...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,zeQZJew1QK,Jill Loyden,1985-06-25,5.0,10.0,USA,NaN,NaN,{},NaN,NaN,NaN,nwsl
700,zeQZJPmZQK,Sydney Leroux,1990-05-07,5.0,7.0,USA,FW,ST,"[2017, 2018, 2019, 2020, 2021, 2022]",NaN,NaN,NaN,nwsl
701,zeQZJXGZQK,Becky Sauerbrunn,1985-06-06,5.0,7.0,USA,DF,CB,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]",NaN,NaN,141.0,nwsl
702,zeQZJXnKQK,Almuth Schult,1991-02-09,5.0,11.0,Germany,GK,GK,2022,NaN,NaN,157.0,nwsl
703,zeQZJXvKQK,Kim Little,1990-06-29,5.0,4.0,Scotland,MF,DM,"[2016, 2022]",NaN,NaN,132.0,nwsl

In [8]:
asa_client.get_player_xgoals(leagues="nwsl", split_by_games=True)

,player_id,game_id,team_id,general_position,minutes_played,shots,shots_on_target,goals,xgoals,xplace,goals_minus_xgoals,key_passes,primary_assists,xassists,primary_assists_minus_xassists,xgoals_plus_xassists,points_added,xpoints_added
0,0Oq632XPQ6,2vQ1ljAxqr,aDQ0lzvQEv,FB,59,2,0,0,0.2031,-0.2031,-0.2031,0,0,0.0000,0.0000,0.2031,0.000,0.2095
1,0Oq632XPQ6,9z5krgAeMA,aDQ0lzvQEv,W,21,1,0,0,0.0319,-0.0319,-0.0319,0,0,0.0000,0.0000,0.0319,0.000,0.0586
2,0Oq632XPQ6,aDQ0mmD2ME,aDQ0lzvQEv,FB,31,0,0,0,0.0000,0.0000,0.0000,0,0,0.0000,0.0000,0.0000,0.000,0.0000
3,0Oq632XPQ6,eV5DEgwYqK,aDQ0lzvQEv,ST,20,0,0,0,0.0000,0.0000,0.0000,0,0,0.0000,0.0000,0.0000,0.000,0.0000
4,0Oq632XPQ6,Vj58gwA2M8,aDQ0lzvQEv,FB,90,1,0,0,0.0148,-0.0148,-0.0148,2,0,0.0510,-0.0510,0.0658,0.000,0.0145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,zeQZJXvKQK,vzqoLzavQa,7vQ7BBzqD1,W,96,3,2,1,0.2723,0.3540,0.7277,1,0,0.0293,-0.0293,0.3016,0.427,0.1250
144,zeQZJXvKQK,vzqoLzX7Qa,7vQ7BBzqD1,DM,95,1,0,0,0.1934,-0.1934,-0.1934,0,0,0.0000,0.0000,0.1934,0.000,0.1874
145,zeQZJXvKQK,Xj5Y3zRxQb,7vQ7BBzqD1,CM,96,0,0,0,0.0000,0.0000,0.0000,3,0,0.1937,-0.1937,0.1937,0.000,0.0000
146,zeQZJXvKQK,XVqKB0mW50,7vQ7BBzqD1,DM,46,0,0,0,0.0000,0.0000,0.0000,2,0,0.0980,-0.0980,0.0980,0.000,0.0000
147,zeQZJXvKQK,zeQZBzxzQK,7vQ7BBzqD1,W,96,3,1,0,0.2154,-0.1684,-0.2154,0,0,0.0000,0.0000,0.2154,0.000,0.0609

In [9]:
asa_client.get_team_xgoals(leagues="nwsl", split_by_games=True)

,team_id,game_id,shots_for,shots_against,goals_for,goals_against,goal_difference,xgoals_for,xgoals_against,xgoal_difference,goal_difference_minus_xgoal_difference,points,xpoints
0,4JMAk47qKg,0Oq61WaA56,18,13,1,2,-1,1.5064,1.3831,0.1233,-1.1233,0,1.402
1,4JMAk47qKg,0Oq64eP7M6,17,6,0,0,0,1.2844,0.1234,1.1610,-1.1611,1,2.353
2,4JMAk47qKg,0Oq6B9nrq6,11,8,1,1,0,0.8628,0.4018,0.4610,-0.4610,1,1.751
3,4JMAk47qKg,0Oq6Oy17Q6,14,11,1,3,-2,1.5658,2.1699,-0.6041,-1.3959,0,1.028
4,4JMAk47qKg,0x5g0jDjq7,15,8,1,3,-2,1.2062,1.7502,-0.5439,-1.4561,0,0.924
...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,zeQZeazqKw,Xj5YDZAaMb,15,11,2,0,2,1.3581,0.7197,0.6384,1.3616,3,0.000
614,zeQZeazqKw,Xj5YEr3x5b,10,4,2,2,0,0.9168,0.5111,0.4057,-0.4057,1,1.713
615,zeQZeazqKw,XVqK8akwQ0,20,19,0,0,0,1.3449,1.3319,0.0130,-0.0130,1,1.377
616,zeQZeazqKw,XVqKB0mW50,10,14,0,2,-2,0.6678,1.9880,-1.3202,-0.6798,0,0.355
617,zeQZeazqKw,xW5pegL0qg,23,3,1,0,1,2.3049,0.0772,2.2277,-1.2277,3,2.869

In [10]:
asa_client.get_game_xgoals(leagues="nwsl")

,game_id,date_time_utc,home_team_id,home_goals,home_team_xgoals,home_player_xgoals,away_team_id,away_goals,away_team_xgoals,away_player_xgoals,goal_difference,team_xgoal_difference,player_xgoal_difference,final_score_difference,home_xpoints,away_xpoints
0,gpMO0D1O5z,2022-10-29 23:59:00 UTC,Pk5LeeNqOW,1,1.8134,1.8134,4wM4rZdqjB,0,0.3443,0.3443,1,1.4691,1.4691,2,0.000,0.000
1,7VqG89LAQv,2022-10-23 23:30:00 UTC,7vQ7BBzqD1,0,1.5070,1.5070,4wM4rZdqjB,2,0.8731,0.8983,-2,0.6338,0.6087,-2,0.000,0.000
2,0Oq66j2rq6,2022-10-23 21:00:00 UTC,Pk5LeeNqOW,2,1.5440,1.5440,7VqG1lYMvW,1,1.2847,1.3199,1,0.2593,0.2241,1,0.000,0.000
3,0x5gEKJ7Q7,2022-10-17 02:00:00 UTC,7VqG1lYMvW,2,2.8942,2.9356,KPqjw8PQ6v,1,1.4419,1.4495,1,1.4524,1.4860,1,0.000,0.000
4,NWMW0Zge5l,2022-10-16 21:00:00 UTC,4JMAk47qKg,1,1.2857,1.2876,4wM4rZdqjB,2,1.5145,1.5191,-1,-0.2288,-0.2315,-1,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,jYQJ6y4EQG,2016-04-18 02:00:00 UTC,Pk5LeeNqOW,2,0.7656,0.7656,XVqKeVKM01,1,0.9702,0.9702,1,-0.2046,-0.2046,1,1.157,1.493
805,Xj5Y3zRxQb,2016-04-17 23:00:00 UTC,7vQ7BBzqD1,1,1.2856,1.2856,raMyrr25d2,2,1.5989,1.5989,-1,-0.3133,-0.3133,-1,1.058,1.667
806,e7MzRogPMr,2016-04-17 00:30:00 UTC,kRQaWa15KZ,0,1.2641,1.2892,xW5pwDBMg1,1,1.9383,1.9383,-1,-0.6742,-0.6492,-1,0.784,1.948
807,N6MmLzjwQE,2016-04-17 00:30:00 UTC,4JMAk47qKg,3,0.9015,0.9046,KPqjw8PQ6v,1,0.3864,0.3864,2,0.5152,0.5183,2,1.786,0.835
808,ljqE3k0YMx,2016-04-16 23:00:00 UTC,aDQ0lzvQEv,1,1.0565,1.0664,4wM4Ezg5jB,0,0.4934,0.4987,1,0.5631,0.5678,1,1.799,0.863

In [12]:
asa_client.get_team_goals_added(leagues="nwsl")["data"][0]

[{'action_type': 'Receiving',
  'num_actions_for': 49980,
  'goals_added_for': 84.5622,
  'num_actions_against': 58107,
  'goals_added_against': 95.8879},
 {'action_type': 'Dribbling',
  'num_actions_for': 22486,
  'goals_added_for': 15.078,
  'num_actions_against': 24882,
  'goals_added_against': 5.0676},
 {'action_type': 'Passing',
  'num_actions_for': 69672,
  'goals_added_for': 16.0359,
  'num_actions_against': 77746,
  'goals_added_against': 20.6389},
 {'action_type': 'Claiming',
  'num_actions_for': 193,
  'goals_added_for': -0.9306000000000001,
  'num_actions_against': 220,
  'goals_added_against': -0.5502},
 {'action_type': 'Fouling',
  'num_actions_for': 1526,
  'goals_added_for': 9.4524,
  'num_actions_against': 1509,
  'goals_added_against': 12.1727},
 {'action_type': 'Shooting',
  'num_actions_for': 2088,
  'goals_added_for': 48.553,
  'num_actions_against': 2042,
  'goals_added_against': 47.9253},
 {'action_type': 'Interrupting',
  'num_actions_for': 20193,
  'goals_added_for': 85.2147,
  'num_actions_against': 19065,
  'goals_added_against': 78.6541}]

In [11]:
asa_client.get_player_goals_added(leagues="nwsl")

,player_id,team_id,general_position,minutes_played,data
0,0Oq632XPQ6,aDQ0lzvQEv,FB,253,"[{'action_type': 'Dribbling', 'goals_added_raw..."
1,0Oq63dogQ6,raMyrr25d2,W,5615,"[{'action_type': 'Dribbling', 'goals_added_raw..."
2,0Oq63dpzQ6,KPqjw8PQ6v,W,42,"[{'action_type': 'Dribbling', 'goals_added_raw..."
3,0Oq63NGdQ6,"[4wM4rZdqjB, eV5D2w9QKn]",FB,3223,"[{'action_type': 'Dribbling', 'goals_added_raw..."
4,0Oq6L6BzM6,aDQ0lzvQEv,W,353,"[{'action_type': 'Dribbling', 'goals_added_raw..."
...,...,...,...,...,...
541,zeQZeYOxqK,XVqKeVKM01,W,43,"[{'action_type': 'Dribbling', 'goals_added_raw..."
542,zeQZJeeNQK,XVqKeVKM01,CB,999,"[{'action_type': 'Dribbling', 'goals_added_raw..."
543,zeQZJPmZQK,"[kRQa8JOqKZ, XVqKeVKM01, kRQaWa15KZ]",ST,7780,"[{'action_type': 'Dribbling', 'goals_added_raw..."
544,zeQZJXGZQK,"[Pk5LeeNqOW, kRQaWa15KZ, eV5D2w9QKn]",CB,10272,"[{'action_type': 'Dribbling', 'goals_added_raw..."
545,zeQZJXvKQK,7vQ7BBzqD1,DM,2490,"[{'action_type': 'Dribbling', 'goals_added_raw..."