In [1]:
from itscalledsoccer.client import AmericanSoccerAnalysis
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from common import Fonts, Images, NWSL

In [3]:
asa_client = AmericanSoccerAnalysis()

Gathering all players
Gathering all teams
Gathering all stadia
Gathering all managers
Gathering all referees
Finished initializing client

In [4]:
teams = asa_client.get_teams(leagues="nwsl")
teams

,team_id,team_name,team_short_name,team_abbreviation,competition
0,4JMAk47qKg,Houston Dash,Houston,HOU,nwsl
1,4wM4Ezg5jB,Boston Breakers,Boston,BOS,nwsl
2,4wM4rZdqjB,Kansas City Current,Kansas City,KC,nwsl
3,7vQ7BBzqD1,OL Reign,Reign,RGN,nwsl
4,7VqG1lYMvW,San Diego Wave FC,San Diego,SD,nwsl
5,aDQ0lzvQEv,Washington Spirit,Washington,WAS,nwsl
6,eV5D2w9QKn,Utah Royals FC,Utah Royals,UTA,nwsl
7,eV5DR6YQKn,Racing Louisville FC,Louisville,LOU,nwsl
8,KPqjw8PQ6v,Chicago Red Stars,Chicago,CHI,nwsl
9,kRQa8JOqKZ,Angel City FC,Angel City,LA,nwsl
10,kRQaWa15KZ,FC Kansas City,Kansas City,KC,nwsl
11,Pk5LeeNqOW,Portland Thorns FC,Portland,POR,nwsl
12,raMyrr25d2,NJ/NY Gotham FC,Gotham FC,NJY,nwsl
13,XVqKeVKM01,Orlando Pride,Orlando,ORL,nwsl
14,xW5pwDBMg1,Western New York Flash,Western New York,WNY,nwsl
15,zeQZeazqKw,North Carolina Courage,North Carolina,NC,nwsl

In [5]:
games = asa_client.get_games(leagues="nwsl")
games

,game_id,date_time_utc,home_score,away_score,home_team_id,away_team_id,referee_id,stadium_id,home_manager_id,away_manager_id,expanded_minutes,season_name,matchday,attendance,knockout_game,last_updated_utc,extra_time,home_penalties,away_penalties,penalties
0,gpMO0D1O5z,2022-10-29 23:59:00 UTC,2,0,Pk5LeeNqOW,4wM4rZdqjB,Xj5YWgaQbd,xW5pwORMg1,xW5pVglQg1,0x5gj0ZM7O,96,2022,23,0,True,2022-10-30 03:31:36 UTC,NaN,NaN,NaN,NaN
1,7VqG89LAQv,2022-10-23 23:30:00 UTC,0,2,7vQ7BBzqD1,4wM4rZdqjB,a35r3kGqL6,9Yqda07QvJ,OlMlY7P5Lz,0x5gj0ZM7O,100,2022,22,21491,True,2022-10-24 01:47:51 UTC,NaN,NaN,NaN,NaN
2,0Oq66j2rq6,2022-10-23 21:00:00 UTC,2,1,Pk5LeeNqOW,7VqG1lYMvW,4wM4mGg5jB,p6qbX06M0G,xW5pVglQg1,7VqGDAjQvW,102,2022,22,22035,True,2022-10-27 15:54:32 UTC,NaN,NaN,NaN,NaN
3,0x5gEKJ7Q7,2022-10-17 02:00:00 UTC,2,1,7VqG1lYMvW,KPqjw8PQ6v,0x5gNljM7O,Oa5wKXY514,7VqGDAjQvW,wvq9bvaQWn,138,2022,21,26215,True,2022-10-21 13:06:03 UTC,1.0,NaN,NaN,NaN
4,NWMW0Zge5l,2022-10-16 21:00:00 UTC,1,2,4JMAk47qKg,4wM4rZdqjB,NWMWR3DQlz,0x5g6ojM7O,9vQ2r1LQK6,0x5gj0ZM7O,105,2022,21,21284,True,2022-10-19 21:49:31 UTC,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,jYQJ6y4EQG,2016-04-18 02:00:00 UTC,2,1,Pk5LeeNqOW,XVqKeVKM01,0Oq6AZ756D,p6qbX06M0G,9z5krYJMA3,e7Mz3xj5r0,98,2016,1,16073,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
805,Xj5Y3zRxQb,2016-04-17 23:00:00 UTC,1,2,7vQ7BBzqD1,raMyrr25d2,2vQ1lzbqrA,gOMnlReqwN,OlMlY7P5Lz,wvq9mKNqWn,96,2016,1,3987,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
806,e7MzRogPMr,2016-04-17 00:30:00 UTC,0,1,kRQaWa15KZ,xW5pwDBMg1,0Oq6mXx56D,NPqxy6XQ9d,vzqo3mNqap,2lqREma5r0,95,2016,1,8022,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
807,N6MmLzjwQE,2016-04-17 00:30:00 UTC,3,1,4JMAk47qKg,KPqjw8PQ6v,7VqGEeeMvW,0x5g6ojM7O,Xj5Yx9RMbd,gOMnwm85wN,96,2016,1,7740,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN
808,ljqE3k0YMx,2016-04-16 23:00:00 UTC,1,0,aDQ0lzvQEv,4wM4Ezg5jB,7VqGv4A5vW,vzqoGO7qap,0Oq6mKg56D,9YqdEXRQvJ,94,2016,1,3578,False,2017-03-10 15:12:59 UTC,NaN,NaN,NaN,NaN

In [6]:
xgoals = asa_client.get_team_xgoals(leagues="nwsl", split_by_games=True)
xgoals

,team_id,game_id,shots_for,shots_against,goals_for,goals_against,goal_difference,xgoals_for,xgoals_against,xgoal_difference,goal_difference_minus_xgoal_difference,points,xpoints
0,4JMAk47qKg,0Oq61WaA56,18,13,1,2,-1,1.5064,1.3831,0.1233,-1.1233,0,1.402
1,4JMAk47qKg,0Oq64eP7M6,17,6,0,0,0,1.2844,0.1234,1.1610,-1.1611,1,2.353
2,4JMAk47qKg,0Oq6B9nrq6,11,8,1,1,0,0.8628,0.4018,0.4610,-0.4610,1,1.751
3,4JMAk47qKg,0Oq6Oy17Q6,14,11,1,3,-2,1.5658,2.1699,-0.6041,-1.3959,0,1.028
4,4JMAk47qKg,0x5g0jDjq7,15,8,1,3,-2,1.2062,1.7502,-0.5439,-1.4561,0,0.924
...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,zeQZeazqKw,Xj5YDZAaMb,15,11,2,0,2,1.3581,0.7197,0.6384,1.3616,3,0.000
614,zeQZeazqKw,Xj5YEr3x5b,10,4,2,2,0,0.9168,0.5111,0.4057,-0.4057,1,1.713
615,zeQZeazqKw,XVqK8akwQ0,20,19,0,0,0,1.3449,1.3319,0.0130,-0.0130,1,1.377
616,zeQZeazqKw,XVqKB0mW50,10,14,0,2,-2,0.6678,1.9880,-1.3202,-0.6798,0,0.355
617,zeQZeazqKw,xW5pegL0qg,23,3,1,0,1,2.3049,0.0772,2.2277,-1.2277,3,2.869

In [7]:
# Join with the teams
xgoals = xgoals.set_index("team_id").join(teams.set_index("team_id")).reset_index()

# Join with the games
xgoals = xgoals.set_index("game_id").join(games.set_index("game_id")).reset_index()

xgoals

,game_id,team_id,shots_for,shots_against,goals_for,goals_against,goal_difference,xgoals_for,xgoals_against,xgoal_difference,...,expanded_minutes,season_name,matchday,attendance,knockout_game,last_updated_utc,extra_time,home_penalties,away_penalties,penalties
0,0Oq61WPA56,Pk5LeeNqOW,18,7,0,0,0,1.5348,0.3807,1.1541,...,97,2019,10,15581,False,2019-07-18 15:08:55 UTC,NaN,NaN,NaN,NaN
1,0Oq61WPA56,eV5D2w9QKn,7,18,0,0,0,0.3807,1.5348,-1.1541,...,97,2019,10,15581,False,2019-07-18 15:08:55 UTC,NaN,NaN,NaN,NaN
2,0Oq61WaA56,4JMAk47qKg,18,13,1,2,-1,1.5064,1.3831,0.1233,...,97,2019,19,4102,False,2019-08-25 05:21:52 UTC,NaN,NaN,NaN,NaN
3,0Oq61WaA56,raMyrr25d2,13,18,2,1,1,1.3831,1.5064,-0.1233,...,97,2019,19,4102,False,2019-08-25 05:21:52 UTC,NaN,NaN,NaN,NaN
4,0Oq61WaX56,KPqjw8PQ6v,11,13,3,0,3,1.0927,1.0075,0.0852,...,96,2019,22,2871,False,2019-09-27 15:16:56 UTC,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1613,zeQZgwwgMK,raMyrr25d2,11,7,1,3,-2,0.8946,1.0075,-0.1130,...,102,2020,7,0,True,2020-07-27 17:30:10 UTC,NaN,NaN,NaN,NaN
1614,zeQZyvmYqK,7VqG1lYMvW,12,13,3,0,3,1.5100,1.4079,0.1021,...,96,2022,8,7145,False,2022-06-21 21:03:04 UTC,NaN,NaN,NaN,NaN
1615,zeQZyvmYqK,raMyrr25d2,13,12,0,3,-3,1.4079,1.5100,-0.1021,...,96,2022,8,7145,False,2022-06-21 21:03:04 UTC,NaN,NaN,NaN,NaN
1616,zeQZyvoYqK,7vQ7BBzqD1,15,8,2,1,1,2.3643,0.5084,1.8560,...,100,2022,16,4588,False,2022-08-27 02:14:36 UTC,NaN,NaN,NaN,NaN
1617,zeQZyvoYqK,XVqKeVKM01,8,15,1,2,-1,0.5084,2.3643,-1.8560,...,100,2022,16,4588,False,2022-08-27 02:14:36 UTC,NaN,NaN,NaN,NaN

In [8]:
xgoals = xgoals[
    [
        "team_name",
        "team_abbreviation",
        "season_name",
        "date_time_utc",
        "goals_for",
        "goals_against",
        "xgoals_for",
        "xgoals_against",
        "knockout_game",
    ]
]
xgoals

,team_name,team_abbreviation,season_name,date_time_utc,goals_for,goals_against,xgoals_for,xgoals_against,knockout_game
0,Portland Thorns FC,POR,2019,2019-06-22 03:00:00 UTC,0,0,1.5348,0.3807,False
1,Utah Royals FC,UTA,2019,2019-06-22 03:00:00 UTC,0,0,0.3807,1.5348,False
2,Houston Dash,HOU,2019,2019-08-25 00:30:00 UTC,1,2,1.5064,1.3831,False
3,NJ/NY Gotham FC,NJY,2019,2019-08-25 00:30:00 UTC,2,1,1.3831,1.5064,False
4,Chicago Red Stars,CHI,2019,2019-09-15 21:00:00 UTC,3,0,1.0927,1.0075,False
...,...,...,...,...,...,...,...,...,...
1613,NJ/NY Gotham FC,NJY,2020,2020-07-23 02:00:00 UTC,1,3,0.8946,1.0075,True
1614,San Diego Wave FC,SD,2022,2022-06-19 20:00:00 UTC,3,0,1.5100,1.4079,False
1615,NJ/NY Gotham FC,NJY,2022,2022-06-19 20:00:00 UTC,0,3,1.4079,1.5100,False
1616,OL Reign,RGN,2022,2022-08-26 23:30:00 UTC,2,1,2.3643,0.5084,False
1617,Orlando Pride,ORL,2022,2022-08-26 23:30:00 UTC,1,2,0.5084,2.3643,False

In [9]:
xgoals.to_csv("xgoals.csv", index=False)