In [25]:
import pandas as pd

In [26]:
results = pd.read_csv("results.csv")
results

     year           team result
0    1991          China      Q
1    1991         Norway      2
2    1991        Denmark      Q
3    1991    New Zealand      G
4    1991  United States      1
..    ...            ...    ...
163  2023      Argentina      ?
164  2023        Germany      ?
165  2023        Morocco      ?
166  2023       Colombia      ?
167  2023    South Korea      ?

[168 rows x 3 columns]

In [27]:
feds = pd.read_csv("federations.csv")
feds

                 team federation
0               China        AFC
1              Norway       UEFA
2             Denmark       UEFA
3         New Zealand        OFC
4       United States   CONCACAF
5              Sweden       UEFA
6              Brazil   CONMEBOL
7               Japan        AFC
8             Germany       UEFA
9               Italy       UEFA
10     Chinese Taipei        AFC
11            Nigeria        CAF
12            England       UEFA
13             Canada   CONCACAF
14          Australia        AFC
15        North Korea        AFC
16             Mexico   CONCACAF
17             Russia       UEFA
18              Ghana        CAF
19             France       UEFA
20        South Korea        AFC
21          Argentina   CONMEBOL
22           Colombia   CONMEBOL
23  Equatorial Guinea        CAF
24        Netherlands       UEFA
25           Thailand        AFC
26        Ivory Coast        CAF
27           Cameroon        CAF
28        Switzerland       UEFA
29            Ecuador   CONMEBOL
30         Costa Rica   CONCACAF
31              Spain       UEFA
32       South Africa        CAF
33            Jamaica   CONCACAF
34           Scotland       UEFA
35              Chile   CONMEBOL
36        Philippines        AFC
37            Ireland       UEFA
38             Zambia        CAF
39              Haiti   CONCACAF
40            Vietnam        AFC
41           Portugal       UEFA
42             Panama   CONCACAF
43            Morocco        CAF

In [28]:
hosts = pd.read_csv("host.csv")
hosts

   year           host
0  1991          China
1  1995         Sweden
2  1999  United States
3  2003  United States
4  2007          China
5  2011        Germany
6  2015         Canada
7  2019         France
8  2023      Australia
9  2023    New Zealand

In [29]:
df = (
    results.pivot(index="team", columns="year", values="result")
    .rename_axis(None, axis=1)
)
df

                  1991 1995 1999 2003 2007 2011 2015 2019 2023
team
Argentina          NaN  NaN  NaN    G    G  NaN  NaN    G    ?
Australia          NaN    G    G    G    Q    Q    Q   16    ?
Brazil               G    G    3    Q    2    Q   16   16    ?
Cameroon           NaN  NaN  NaN  NaN  NaN  NaN   16   16  NaN
Canada             NaN    G    G    4    G    G    Q   16    ?
Chile              NaN  NaN  NaN  NaN  NaN  NaN  NaN    G  NaN
China                Q    4    2    Q    Q  NaN    Q   16    ?
Chinese Taipei       Q  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Colombia           NaN  NaN  NaN  NaN  NaN    G   16  NaN    ?
Costa Rica         NaN  NaN  NaN  NaN  NaN  NaN    G  NaN    ?
Denmark              Q    Q    G  NaN    G  NaN  NaN  NaN    ?
Ecuador            NaN  NaN  NaN  NaN  NaN  NaN    G  NaN  NaN
England            NaN    Q  NaN  NaN    Q    Q    3    4    ?
Equatorial Guinea  NaN  NaN  NaN  NaN  NaN    G  NaN  NaN  NaN
France             NaN  NaN  NaN    G  NaN    4    Q    Q    ?
Germany              4    2    Q    1    1    Q    4    Q    ?
Ghana              NaN  NaN    G    G    G  NaN  NaN  NaN  NaN
Haiti              NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Ireland            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Italy                Q  NaN    G  NaN  NaN  NaN  NaN    Q    ?
Ivory Coast        NaN  NaN  NaN  NaN  NaN  NaN    G  NaN  NaN
Jamaica            NaN  NaN  NaN  NaN  NaN  NaN  NaN    G    ?
Japan                G    Q    G    G    G    1    2   16    ?
Mexico             NaN  NaN    G  NaN  NaN    G    G  NaN  NaN
Morocco            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Netherlands        NaN  NaN  NaN  NaN  NaN  NaN   16    2    ?
New Zealand          G  NaN  NaN  NaN    G    G    G    G    ?
Nigeria              G    G    Q    G    G    G    G   16    ?
North Korea        NaN  NaN    G    G    Q    G  NaN  NaN  NaN
Norway               2    1    4    Q    4    G   16    Q    ?
Panama             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Philippines        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Portugal           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Russia             NaN  NaN    Q    Q  NaN  NaN  NaN  NaN  NaN
Scotland           NaN  NaN  NaN  NaN  NaN  NaN  NaN    G  NaN
South Africa       NaN  NaN  NaN  NaN  NaN  NaN  NaN    G    ?
South Korea        NaN  NaN  NaN    G  NaN  NaN   16    G    ?
Spain              NaN  NaN  NaN  NaN  NaN  NaN    G   16    ?
Sweden               3    Q    Q    2    G    3   16    3    ?
Switzerland        NaN  NaN  NaN  NaN  NaN  NaN   16  NaN    ?
Thailand           NaN  NaN  NaN  NaN  NaN  NaN    G    G  NaN
United States        1    3    1    3    3    2    1    1    ?
Vietnam            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?
Zambia             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?

In [30]:
df = (
    df.join(feds.set_index("team"))
    .sort_index(axis=0)
    .sort_values(["federation"], kind="stable")
)
df

                  1991 1995 1999 2003 2007 2011 2015 2019 2023 federation
team
Australia          NaN    G    G    G    Q    Q    Q   16    ?        AFC
China                Q    4    2    Q    Q  NaN    Q   16    ?        AFC
Chinese Taipei       Q  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN        AFC
Japan                G    Q    G    G    G    1    2   16    ?        AFC
North Korea        NaN  NaN    G    G    Q    G  NaN  NaN  NaN        AFC
Philippines        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?        AFC
South Korea        NaN  NaN  NaN    G  NaN  NaN   16    G    ?        AFC
Thailand           NaN  NaN  NaN  NaN  NaN  NaN    G    G  NaN        AFC
Vietnam            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?        AFC
Cameroon           NaN  NaN  NaN  NaN  NaN  NaN   16   16  NaN        CAF
Equatorial Guinea  NaN  NaN  NaN  NaN  NaN    G  NaN  NaN  NaN        CAF
Ghana              NaN  NaN    G    G    G  NaN  NaN  NaN  NaN        CAF
Ivory Coast        NaN  NaN  NaN  NaN  NaN  NaN    G  NaN  NaN        CAF
Morocco            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?        CAF
Nigeria              G    G    Q    G    G    G    G   16    ?        CAF
South Africa       NaN  NaN  NaN  NaN  NaN  NaN  NaN    G    ?        CAF
Zambia             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?        CAF
Canada             NaN    G    G    4    G    G    Q   16    ?   CONCACAF
Costa Rica         NaN  NaN  NaN  NaN  NaN  NaN    G  NaN    ?   CONCACAF
Haiti              NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?   CONCACAF
Jamaica            NaN  NaN  NaN  NaN  NaN  NaN  NaN    G    ?   CONCACAF
Mexico             NaN  NaN    G  NaN  NaN    G    G  NaN  NaN   CONCACAF
Panama             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?   CONCACAF
United States        1    3    1    3    3    2    1    1    ?   CONCACAF
Argentina          NaN  NaN  NaN    G    G  NaN  NaN    G    ?   CONMEBOL
Brazil               G    G    3    Q    2    Q   16   16    ?   CONMEBOL
Chile              NaN  NaN  NaN  NaN  NaN  NaN  NaN    G  NaN   CONMEBOL
Colombia           NaN  NaN  NaN  NaN  NaN    G   16  NaN    ?   CONMEBOL
Ecuador            NaN  NaN  NaN  NaN  NaN  NaN    G  NaN  NaN   CONMEBOL
New Zealand          G  NaN  NaN  NaN    G    G    G    G    ?        OFC
Denmark              Q    Q    G  NaN    G  NaN  NaN  NaN    ?       UEFA
England            NaN    Q  NaN  NaN    Q    Q    3    4    ?       UEFA
France             NaN  NaN  NaN    G  NaN    4    Q    Q    ?       UEFA
Germany              4    2    Q    1    1    Q    4    Q    ?       UEFA
Ireland            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?       UEFA
Italy                Q  NaN    G  NaN  NaN  NaN  NaN    Q    ?       UEFA
Netherlands        NaN  NaN  NaN  NaN  NaN  NaN   16    2    ?       UEFA
Norway               2    1    4    Q    4    G   16    Q    ?       UEFA
Portugal           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    ?       UEFA
Russia             NaN  NaN    Q    Q  NaN  NaN  NaN  NaN  NaN       UEFA
Scotland           NaN  NaN  NaN  NaN  NaN  NaN  NaN    G  NaN       UEFA
Spain              NaN  NaN  NaN  NaN  NaN  NaN    G   16    ?       UEFA
Sweden               3    Q    Q    2    G    3   16    3    ?       UEFA
Switzerland        NaN  NaN  NaN  NaN  NaN  NaN   16  NaN    ?       UEFA

In [31]:
df.to_csv("merged.csv")