In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/stats_2023.csv")
df

,result_id,player_id,avg_speed,distance_high_speed_running,distance_high_speed_sprinting,distance_jogging,distance_low_speed_sprinting,distance_walking,speed_runs,sprints,...,corners,goal_kicks,goals_inside_the_penalty_area,attempt_at_goal_inside_the_penalty_area_on_target,attempt_at_goal_from_free_kicks,fouls_for,offsides,attempt_at_goal_blocked,player_name,date
0,131872,467661,5.59,1892.743298,293.136394,3384.648332,315.613306,3478.302132,162,39,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Mathilde HARVIKEN,2023-07-20T19:00:00Z
1,131872,420294,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sophie ROMAN HAUG,2023-07-20T19:00:00Z
2,131872,467662,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sara HORTE,2023-07-20T19:00:00Z
3,131872,467653,5.75,2082.699250,123.189445,3230.399475,469.715150,2955.660425,182,38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Thea BJELDE,2023-07-20T19:00:00Z
4,131872,467666,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marit BRATBERG LUND,2023-07-20T19:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,131896,466811,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,Thi Thuy Nga TRAN,2023-07-22T13:00:00Z
269,131896,466806,5.73,996.392320,0.000000,1497.419140,152.451260,1397.537280,79,13,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,Thi Hai Linh TRAN,2023-07-22T13:00:00Z
270,131896,466786,5.54,651.356156,63.423736,848.923900,162.768880,1079.606692,49,12,...,0.0,0.0,0.0,0.0,NaN,2.0,0.0,0.0,Nhu HUYNH,2023-07-22T13:00:00Z
271,131896,466779,6.93,1037.676544,62.663744,1416.726464,271.688960,1593.324288,83,23,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,Thi My Anh NGUYEN,2023-07-22T13:00:00Z
272,131896,466792,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,Thi Hang KHONG,2023-07-22T13:00:00Z

In [10]:
df[df["result_id"] == 131896][["distance_walking", "player_name"]].sort_values("distance_walking", ascending=False)

     distance_walking            player_name
253       2245.546160         Thi Loan HOANG
250       2087.714508          Thi Thao THAI
255       2069.084631         Thi Diem My LE
254       2063.482014           Thi Thu TRAN
232       1985.200764          Lindsey HORAN
228       1943.218581           Sophia SMITH
252       1906.866922      Thi Thu Thao TRAN
231       1903.644709          Andi SULLIVAN
262       1857.579264        Thi Van Su NGAN
230       1768.941800            Naomi GIRMA
236       1731.840720             Julie ERTZ
256       1690.401592        Thi Kieu CHUONG
227       1605.802914          Alyssa NAEHER
271       1593.324288      Thi My Anh NGUYEN
234       1529.156796          Megan RAPINOE
263       1437.710816     Thi Kim Thanh TRAN
269       1397.537280      Thi Hai Linh TRAN
240       1374.754662           Rose LAVELLE
229       1231.906984              Emily FOX
246       1132.538048           Crystal DUNN
270       1079.606692              Nhu HUYNH
237       1077.252480         Trinity RODMAN
259        901.463397           Hai Yen PHAM
249        851.443884        Alyssa THOMPSON
241        598.591105        Savannah DEMELO
267        545.321410   Thi Bich Thuy NGUYEN
245        527.241393           Sofia HUERTA
264        503.266470   Thi Thu Thuong LUONG
239        454.231030           Kelley OHARA
265        410.253145          Thi Van DUONG
243        375.131400            Alex MORGAN
266         33.822144  Thi Tuyet Dung NGUYEN
268          0.000000      Thi Thuy Nga TRAN
261          0.000000   Thi Thuy Hang NGUYEN
233          0.000000         Ashley SANCHEZ
260          0.000000      Thi Kieu Oanh DAO
258          0.000000             Thi Hoa VU
257          0.000000   Thi Thanh Nha NGUYEN
235          0.000000          Lynn WILLIAMS
238          0.000000           Casey MURPHY
251          0.000000    Thi Thuy Trang TRAN
248          0.000000          Emily SONNETT
247          0.000000             Alana COOK
244          0.000000       Aubrey KINGSBURY
242          0.000000          Kristie MEWIS
272          0.000000         Thi Hang KHONG